import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: {
		width: "device-width",
		initialScale: 1,
	},
	icons: {
		icon: "/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${montserrat.className}`}>
				<div className="bg-light w-full min-h-screen h-full">
					<NavBar />
					<div className="flex min-h-screen items-center text-dark">
						{children}
					</div>
				</div>
			</body>
		</html>
	);
}
