import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-mont" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: {
		width: "device-width",
		initialScale: 1,
	},
	icons: {
		icon: "/favicon.ico",
	},
};
// BlinkMacSystemFont, Roboto, "Noto Color Emoji"

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${montserrat.variable} font-mont`}>
				<div className="bg-light w-full min-h-screen h-full">
					<NavBar />
					<div className="flex min-h-screen items-center text-dark">
						{children}
					</div>
					<Footer />
				</div>
			</body>
		</html>
	);
}
